version: '3.3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "4000:2000"
    environment:
      - PYTHONUNBUFFERED=1